version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    env_file:
      - .env

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: ["bun", "run", "--watch", "src/index.ts"]
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
